[workspace]
members = ["cargo:."]

[dist]
cargo-dist-version = "0.32.0"
ci = "github"
installers = ["powershell", "msi"]
targets = ["x86_64-pc-windows-msvc"]
install-path = "CARGO_HOME"
install-updater = false
