[project]
name = "laravel-app"
domain = "laravel-app.localhost"

[language]
php = "8.3.1"

[service.mysql]
version = "8.0.35"
schema = "laravel_app"

[tool.composer]
version = "2.7.7"

[run]
command = "php -S 127.0.0.1:{port} -t public"
